#!/bin/bash
#
# Git hook: prepare-pr-msg
#

# Get branch.
branch=$(git symbolic-ref --short HEAD)

# Convert branch' slashes and dashes to white spaces.
branch=$(echo $branch | sed -e 's/-/ /g' | sed -e 's/\// /g')

# Check if feature branch and has an integer ticket number.
msg=0
ticket=''
if [ $(echo $branch | awk '{print $1}') == 'feature' ] && [[ $(echo $branch | awk '{print $3}') =~ ^-?[0-9]+$ ]]; then
  project=$(echo $branch | awk '{print $2}')
  ticket=$(echo $branch | awk '{print $3}')
  msg=1
fi

# Get branch's project-ticket number.
if [ $msg == 1 ]; then
  ticket="$project-$ticket: "
  echo "[$ticket]  "
  echo "Jira"
  echo "-----"
  echo "https://prometprojects.atlassian.net/browse/$ticket"
  echo "Detail(s)"
  echo "-----"
  echo ""
fi
